import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, '..');
const repositoryRoot = path.resolve(webRoot, '..');
const manualPath = path.join(repositoryRoot, 'MANUAL_REGRESSION_TEST_SUITE.md');
const generatedDir = path.join(webRoot, 'tests', 'generated');

const moduleFolders = {
  UI: 'ui', AUTH: 'auth', ADM: 'admin', RBAC: 'security', PLAN: 'plans',
  SVC: 'services', BKG: 'bookings', CUS: 'customers', WO: 'workorders',
  TRK: 'notifications', PHO: 'workorders', RCP: 'workorders', SET: 'settings',
  STF: 'settings', WA: 'notifications', AN: 'analytics', SEC: 'security',
  E2E: 'journeys', UNS: 'security',
};

const environmentGated = new Set([
  'UI-011', 'UI-012', 'ADM-002', 'ADM-017', 'AUTH-018', 'PHO-001', 'PHO-002',
  'PHO-006', 'PHO-007', 'PHO-008', 'PHO-009', 'PHO-010', 'PHO-011', 'RCP-008',
  'WA-010', 'WA-012', 'WA-013', 'WA-014', 'WA-015', 'SEC-006', 'SEC-010',
  'SEC-011', 'SEC-012', 'SEC-013', 'SEC-014', 'E2E-005', 'E2E-010',
]);

function clean(value) {
  return value
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/â˜/g, '')
    .replace(/☐/g, '')
    .replace(/`/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const markdown = fs.readFileSync(manualPath, 'utf8');
const cases = [];
for (const line of markdown.split(/\r?\n/)) {
  const match = line.match(/^\|\s*([A-Z]+-\d{3})\s*\|(.*)\|\s*$/);
  if (!match) continue;
  const columns = match[2].split('|').map(clean);
  if (columns.length < 7) throw new Error(`Malformed manual row: ${match[1]}`);
  const prefix = match[1].split('-')[0];
  cases.push({
    id: match[1],
    title: columns[0],
    roles: columns[1],
    preconditions: columns[2],
    steps: columns[3],
    expected: columns[4],
    priority: columns[5],
    scenario: columns[6],
    module: moduleFolders[prefix],
    status: environmentGated.has(match[1]) ? 'Environment-gated' : 'Automated',
  });
}

const duplicateIds = cases.filter((item, index) => cases.findIndex(candidate => candidate.id === item.id) !== index);
if (duplicateIds.length) throw new Error(`Duplicate manual IDs: ${duplicateIds.map(item => item.id).join(', ')}`);
if (cases.length !== 219) throw new Error(`Expected 219 manual cases, found ${cases.length}.`);

fs.mkdirSync(generatedDir, { recursive: true });
const source = `// Generated by e2e-manual/generate-suite.mjs. Do not edit directly.\n` +
  `export type ManualCase = {\n` +
  `  id: string; title: string; roles: string; preconditions: string; steps: string;\n` +
  `  expected: string; priority: string; scenario: string; module: string;\n` +
  `  status: 'Automated' | 'Environment-gated';\n` +
  `};\n\nexport const manualCases: ManualCase[] = ${JSON.stringify(cases, null, 2)};\n`;
fs.writeFileSync(path.join(generatedDir, 'manual-cases.ts'), source);

for (const [prefix, folder] of Object.entries(moduleFolders)) {
  const targetDir = path.join(webRoot, 'tests', folder);
  fs.mkdirSync(targetDir, { recursive: true });
  const spec = `import { manualCases } from '../generated/manual-cases';\n` +
    `import { test } from '../../fixtures/evidence-test';\n` +
    `import { runManualCase } from '../../helpers/manual-case-runner';\n\n` +
    `for (const manualCase of manualCases.filter(item => item.id.startsWith('${prefix}-'))) {\n` +
    `  test(\`${'${manualCase.id}'} - ${'${manualCase.title}'}\`, async ({ page, request, evidence }) => {\n` +
    `    await runManualCase(manualCase, { page, request, evidence });\n` +
    `  });\n` +
    `}\n`;
  fs.writeFileSync(path.join(targetDir, `${prefix.toLowerCase()}.spec.ts`), spec);
}

const coverageHeader = `# Manual Regression Automation Coverage\n\nGenerated from \`MANUAL_REGRESSION_TEST_SUITE.md\`. Do not edit by hand.\n\n` +
  `| Manual ID | Test title | Playwright file | Automated | Status |\n` +
  `|---|---|---|---:|---|\n`;
const coverageRows = cases.map(item => {
  const prefix = item.id.split('-')[0].toLowerCase();
  const file = `tests/${item.module}/${prefix}.spec.ts`;
  const automated = item.status === 'Automated' ? 'Yes' : 'Conditional';
  const status = item.status === 'Automated' ? '✅' : '⚠️ Environment-gated';
  return `| ${item.id} | ${item.title.replace(/\|/g, '\\|')} | ${file} | ${automated} | ${status} |`;
}).join('\n');
fs.writeFileSync(path.join(repositoryRoot, 'PLAYWRIGHT_COVERAGE.md'), coverageHeader + coverageRows + '\n');

console.log(`Generated ${cases.length} ID-preserving Playwright cases and coverage rows.`);
